// Generated by https://quicktype.io

namespace CanvasCourseObjects.CourseBlueprintSubscription
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class CanvasBlueprintSubscription
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("template_id")]
        public long TemplateId { get; set; }

        [JsonProperty("blueprint_course")]
        public BlueprintCourse BlueprintCourse { get; set; }
    }

    public partial class BlueprintCourse
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("course_code")]
        public string CourseCode { get; set; }

        [JsonProperty("sis_course_id")]
        public string SisCourseId { get; set; }

        [JsonProperty("term_name")]
        public string TermName { get; set; }
    }

    public partial class CanvasBlueprintSubscription
    {
        public static CanvasBlueprintSubscription FromJson(string json) => JsonConvert.DeserializeObject<CanvasBlueprintSubscription>(json, CanvasCourseObjects.CourseBlueprintSubscription.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this CanvasBlueprintSubscription self) => JsonConvert.SerializeObject(self, CanvasCourseObjects.CourseBlueprintSubscription.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
